using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PolicyCheck.Models.ViewModel
{
    public class MainVM
    {
        public int id { get; set; }
        public string PPostCode { get; set; }
        public Nullable<int> PYearBuilt { get; set; }
        public string PTypeOfHouse { get; set; }
        public string PWalls { get; set; }
        public string PRoof { get; set; }
        public Nullable<int> PFlatPercent { get; set; }
        public Nullable<int> PBedrooms { get; set; }
        public Nullable<int> PRooms { get; set; }
        public Nullable<int> PFloors { get; set; }
        public Nullable<int> PBathrooms { get; set; }
        public string PExtended { get; set; }
        public Nullable<int> PYearExtended { get; set; }
        public Nullable<int> PHeatingPrimary { get; set; }
        public Nullable<int> PHeatingSecondary { get; set; }
        public string PPrelimQuestions { get; set; }
        public string PPqInsuranceDeclined { get; set; }
        public string PPqConvictions { get; set; }
        public string PPqBankrupt { get; set; }
        public string PPqStormFlood { get; set; }
        public string PPqSubsidence { get; set; }
        public string PPqLandslip { get; set; }
        public string PPqGroundHeave { get; set; }
        public string PPqInGoodRepair { get; set; }
        public string PPqNearRiverQuarry { get; set; }
        public string PPqNearRQDistance { get; set; }
        public string PPqBuildingListed { get; set; }
        public string PPqRepairedMonitored { get; set; }
        public string PPqUnderpinned { get; set; }
        public string PUseOccupancy { get; set; }
        public string PuoAccomodation { get; set; }
        public string PuoResidence { get; set; }
        public string PuoUnnocupied { get; set; }
        public string PuoBusinessUse { get; set; }
        public Nullable<int> PuoStock { get; set; }
        public Nullable<int> PuoEquipment { get; set; }
        public string PuoHolidayHome { get; set; }
        public string PuoPayingGuests { get; set; }
        public string PuoSmokers { get; set; }
        public Nullable<int> PuoNooAdults { get; set; }
        public Nullable<int> PuoNooChildren { get; set; }
        public string PSecurity { get; set; }
        public string PsFinalExitDoors { get; set; }
        public string PsOtherDoors { get; set; }
        public string PsPatioDoors { get; set; }
        public string PsWindows { get; set; }
        public string PsNeighbourhoodWatch { get; set; }
        public string PsSmokeAlarm { get; set; }
        public string PsSelfContained { get; set; }
        public string PsIntruderAlarm { get; set; }
        public string PsAlarmType { get; set; }
        public string PsAccredationDetailsOne { get; set; }
        public string PsSpecificationContract { get; set; }
        public Nullable<System.DateTime> PsDateInstalled { get; set; }
        public string PsMaintainer { get; set; }
        public string PsAccreditationDetailsTwo { get; set; }
        public string PsrSecurityReports { get; set; }
        public string PsrRICSFSVASURVEY { get; set; }
        public Nullable<System.DateTime> PsrRFSDate { get; set; }
        public string PsrRFSSurveyorsName { get; set; }
        public string PsrRFSDateProofRec { get; set; }
        public string PsrStructuralER { get; set; }
        public Nullable<System.DateTime> PsrStructuralERDate { get; set; }
        public string PsrStructuralEnginnersName { get; set; }
        public string PsrNHBCguarantee { get; set; }
        public Nullable<System.DateTime> PsrExpires { get; set; }
        public string POtherDetails { get; set; }
        public string MpSex { get; set; }
        public Nullable<System.DateTime> MpDOB { get; set; }
        public Nullable<int> MpAge { get; set; }
        public string EmployDetails { get; set; }
        public string MpEDOccOne { get; set; }
        public string MpEDOccOneBusiness { get; set; }
        public string MpEDOccOneStatus { get; set; }
        public string MpEDOccOneFullPart { get; set; }
        public string MpEDOccTwo { get; set; }
        public string MpEDOccTwoBusiness { get; set; }
        public string MpEDOccTwoStatus { get; set; }
        public string MpEDOccTwoFullPart { get; set; }
        public string MpPersonalDetails { get; set; }
        public string MpPersonalDetailsTitle { get; set; }
        public string MpSurname { get; set; }
        public string MpForenames { get; set; }
        public string MpAtRiskAddress { get; set; }
        public string MpFirstTimeBuyer { get; set; }
        public string MpConvictions { get; set; }
        public string MpClaimsLosses { get; set; }
        public string CBuildingsAndContents { get; set; }
        public string CBCoverType { get; set; }
        public Nullable<int> CBSumInsured { get; set; }
        public Nullable<int> CBVolExcess { get; set; }
        public string CBXSBuyBack { get; set; }
        public string CBPrevInsurer { get; set; }
        public string CBPrevInsurerName { get; set; }
        public string CBPrevInsurerPolicyNo { get; set; }
        public Nullable<System.DateTime> CBPrevInsurerDateLapse { get; set; }
        public Nullable<int> CBPrevInsurerYearsNCB { get; set; }
        public string CBPrevInsurerNCBProofRec { get; set; }
        public Nullable<int> CBPrevInsurerYearsInsured { get; set; }
        public string CBPrevInsurerTransferFeeRec { get; set; }
        public string CBPrevInsurerPOPRec { get; set; }
        public string CCCoverType { get; set; }
        public Nullable<int> CCSumInsuredValue { get; set; }
        public Nullable<int> CCSumInsuredOneItem { get; set; }
        public Nullable<int> CCValuablesValue { get; set; }
        public Nullable<int> CCValuablesOneItem { get; set; }
        public Nullable<int> CCVolExcess { get; set; }
        public string CCXSBuyBack { get; set; }
        public string CCPrevInsurer { get; set; }
        public string CCPrevInsurerName { get; set; }
        public string CCPrevInsurerPolicyNo { get; set; }
        public Nullable<System.DateTime> CCPrevInsurerDateLapse { get; set; }
        public Nullable<int> CCPrevInsurerYearsNCB { get; set; }
        public string CCPrevInsurerNCBProofRec { get; set; }
        public Nullable<int> CCPrevInsurerYearsInsured { get; set; }
        public string CAllRisks { get; set; }
        public Nullable<int> CAllRiskUnspecEffectsValue { get; set; }
        public Nullable<int> CAllRiskUnspecEffectsOneItem { get; set; }
        public string CAllRiskUnspecEffectsTerritory { get; set; }
        public Nullable<int> CAllRisksValuablesUnspecValue { get; set; }
        public Nullable<int> CAllRisksValuablesUnspecOneItem { get; set; }
        public string CAllRisksValuablesUnspecTerritory { get; set; }
        public Nullable<int> CAllRisksPhotoUnspecValue { get; set; }
        public Nullable<int> CAllRisksPhotoUnspecOneItem { get; set; }
        public string CAllRisksPhotoUnspecTerritory { get; set; }
        public Nullable<int> CAllRisksSportsUnspecValue { get; set; }
        public Nullable<int> CAllRisksSportsUnspecOneItem { get; set; }
        public string CAllRisksSportsUnspecTerritory { get; set; }
        public string CAllRiskBicycles { get; set; }
        public Nullable<int> CAllRisksMoneyValue { get; set; }
        public string CAllRisksMoneyTerritory { get; set; }
        public Nullable<int> CAllRisksCreditCardsValue { get; set; }
        public string CAllRiskCreditCardsTerritory { get; set; }
        public Nullable<int> CAllRisksFreezerContentsValue { get; set; }
        public int CAllRisksFreezerContentsAge { get; set; }
        public string CSpecifiedItems { get; set; }
        public string AOLegalExpenses { get; set; }
        public string AOMotorPolicy { get; set; }
        public string AOCurrentMotorInsurer { get; set; }
        public string AOCaravans { get; set; }
        public string AOBoats { get; set; }
        public string AOSearchesConsent { get; set; }
        public string AOSchemeNo { get; set; }
        public Nullable<System.DateTime> AOCoverDate { get; set; }

        public int CommunicationAddressPolicyId { get; set; }
        public string CANumberName { get; set; }
        public string CAStreet { get; set; }
        public string CATown { get; set; }
        public string CACounty { get; set; }
        public string CAPostCode { get; set; }

        public int InterestedPartyPolicyId { get; set; }
        public string IPType { get; set; }
        public string IPName { get; set; }
        public string IPNumberName { get; set; }
        public string IPStreet { get; set; }
        public string IPTown { get; set; }
        public string IPCounty { get; set; }
        public string IPPostCode { get; set; }
        public string IPRefMortgageNo { get; set; }

        public int RiskPropertyAddressPolicyId { get; set; }
        public string RPNumberName { get; set; }
        public string RPStreet { get; set; }
        public string RPTown { get; set; }
        public string RPCounty { get; set; }
        public string RPPostCode { get; set; }

        public int BoatPolicyId { get; set; }
        public string BoatType { get; set; }
        public string BoatName { get; set; }
        public byte[] BoatSailNo { get; set; }
        public string BoatClass { get; set; }
        public string BoatModel { get; set; }
        public Nullable<System.DateTime> BoatManufactured { get; set; }
        public Nullable<System.DateTime> BoatPurchased { get; set; }
        public Nullable<int> BoatMaximumSpeed { get; set; }
        public string BoatOver5m { get; set; }
        public string BoatUnusedAtMooring { get; set; }
        public string BoatEngineDetailsType { get; set; }
        public string BoatEngineDetailsMake { get; set; }
        public string BoatEngineDetailsSerNo { get; set; }
        public Nullable<System.DateTime> BoatEngineDetailsMade { get; set; }
        public string BoatEngineDetailsHP { get; set; }
        public Nullable<int> BoatCoverDetailsCraftGeneral { get; set; }
        public Nullable<int> BoatCoverDetailsOutboardMotor { get; set; }
        public Nullable<int> BoatCoverDetailsRoadTrailer { get; set; }
        public Nullable<int> BoatCoverDetailsLaunchingTrolley { get; set; }

        public int CaravanPolicyId { get; set; }
        public byte[] CaravanType { get; set; }
        public string CaravanMake { get; set; }
        public string caravanModel { get; set; }
        public string caravanVIN { get; set; }
        public string caravanSerialNumber { get; set; }
        public Nullable<System.DateTime> caravanManufactured { get; set; }
        public Nullable<System.DateTime> caravanPurchased { get; set; }
        public Nullable<int> caravanPricePaid { get; set; }
        public string caravanLetHireReward { get; set; }
        public string caravanRiskUnused { get; set; }
        public string caravanKeptOnSite { get; set; }
        public Nullable<int> CaravanAndFittings { get; set; }
        public Nullable<int> caravanPersonalPossesions { get; set; }
        public Nullable<int> caravanHighestValueItem { get; set; }

    }
}