//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyCheck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AOBoatDetail
    {
        public int BoatPolicyId { get; set; }
        public int BoatId { get; set; }
        public string BoatType { get; set; }
        public string BoatName { get; set; }
        public string BoatSailNo { get; set; }
        public string BoatClass { get; set; }
        public string BoatModel { get; set; }
        public Nullable<System.DateTime> BoatManufactured { get; set; }
        public Nullable<System.DateTime> BoatPurchased { get; set; }
        public Nullable<int> BoatMaximumSpeed { get; set; }
        public string BoatOver5m { get; set; }
        public string BoatUnusedAtMooring { get; set; }
        public string BoatEngineDetailsType { get; set; }
        public string BoatEngineDetailsMake { get; set; }
        public string BoatEngineDetailsSerNo { get; set; }
        public Nullable<System.DateTime> BoatEngineDetailsMade { get; set; }
        public Nullable<int> BoatEngineDetailsHP { get; set; }
        public Nullable<int> BoatCoverDetailsCraftGeneral { get; set; }
        public Nullable<int> BoatCoverDetailsOutboardMotor { get; set; }
        public Nullable<int> BoatCoverDetailsRoadTrailer { get; set; }
        public Nullable<int> BoatCoverDetailsLaunchingTrolley { get; set; }
    
        public virtual PolicyMain PolicyMain { get; set; }
    }
}
