//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyCheck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AOCaravanDetail
    {
        public int CaravanPolicyId { get; set; }
        public int CaravanId { get; set; }
        public string CaravanType { get; set; }
        public string CaravanMake { get; set; }
        public string caravanModel { get; set; }
        public string caravanVIN { get; set; }
        public string caravanSerialNumber { get; set; }
        public Nullable<System.DateTime> caravanManufactured { get; set; }
        public Nullable<System.DateTime> caravanPurchased { get; set; }
        public Nullable<int> caravanPricePaid { get; set; }
        public string caravanLetHireReward { get; set; }
        public string caravanRiskUnused { get; set; }
        public string caravanKeptOnSite { get; set; }
        public Nullable<int> CaravanAndFittings { get; set; }
        public Nullable<int> caravanPersonalPossesions { get; set; }
        public Nullable<int> caravanHighestValueItem { get; set; }
    
        public virtual PolicyMain PolicyMain { get; set; }
    }
}
