//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyCheck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CBuildingsPrevInsurance
    {
        public int PrevInsPolicyId { get; set; }
        public int PrevInsId { get; set; }
        public string InsurerName { get; set; }
        public string InsurerNameOther { get; set; }
        public string PolicyNo { get; set; }
        public Nullable<System.DateTime> DateLapsed { get; set; }
        public Nullable<int> YearsNCB { get; set; }
        public string ProofNCB { get; set; }
        public Nullable<int> NoOfYearsIns { get; set; }
        public string TransferFeePaid { get; set; }
        public string ProofOfPaymentRec { get; set; }
    
        public virtual PolicyMain PolicyMain { get; set; }
    }
}
