//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyCheck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCContentsPrevInsurance
    {
        public int CPrevInsPolicyId { get; set; }
        public int CPrevInsId { get; set; }
        public string CinsurerName { get; set; }
        public string CInsurerNameOther { get; set; }
        public string CPolicyNo { get; set; }
        public Nullable<System.DateTime> CDateLapsed { get; set; }
        public Nullable<int> CYearsNCB { get; set; }
        public string CproofNCB { get; set; }
        public Nullable<int> CNoOfYearsIns { get; set; }
    
        public virtual PolicyMain PolicyMain { get; set; }
    }
}
