//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyCheck.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class OpenGIABICodesEntities1 : DbContext
    {
        internal readonly IEnumerable<object> SpecifiedItem_Categories;

        public OpenGIABICodesEntities1()
            : base("name=OpenGIABICodesEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alarm_AccredDetails2> Alarm_AccredDetails2 { get; set; }
        public virtual DbSet<Alarm_MaintenanceCompany> Alarm_MaintenanceCompany { get; set; }
        public virtual DbSet<Alarm_Type> Alarm_Type { get; set; }
        public virtual DbSet<Buildings_Insurer> Buildings_Insurer { get; set; }
        public virtual DbSet<Claims_Sections> Claims_Sections { get; set; }
        public virtual DbSet<Contents_Insurer> Contents_Insurer { get; set; }
        public virtual DbSet<Home_ClaimType> Home_ClaimType { get; set; }
        public virtual DbSet<Home_InterestedPartyName> Home_InterestedPartyName { get; set; }
        public virtual DbSet<Motor_AlarmSecurityFitted> Motor_AlarmSecurityFitted { get; set; }
        public virtual DbSet<Motor_AlarmSecurityMake> Motor_AlarmSecurityMake { get; set; }
        public virtual DbSet<Motor_ClaimType> Motor_ClaimType { get; set; }
        public virtual DbSet<Motor_ConvictionType> Motor_ConvictionType { get; set; }
        public virtual DbSet<Motor_IncidentType> Motor_IncidentType { get; set; }
        public virtual DbSet<Motor_LicenseCountry> Motor_LicenseCountry { get; set; }
        public virtual DbSet<Motor_LicenseType> Motor_LicenseType { get; set; }
        public virtual DbSet<Motor_PermittedDrivers> Motor_PermittedDrivers { get; set; }
        public virtual DbSet<Motor_TrackerSecurityFitted> Motor_TrackerSecurityFitted { get; set; }
        public virtual DbSet<Motor_TrackerSecurityMake> Motor_TrackerSecurityMake { get; set; }
        public virtual DbSet<Motor_VehicleCoverType> Motor_VehicleCoverType { get; set; }
        public virtual DbSet<Motor_VehicleKeeper> Motor_VehicleKeeper { get; set; }
        public virtual DbSet<Motor_VehicleModification> Motor_VehicleModification { get; set; }
        public virtual DbSet<Motor_VehicleOwner> Motor_VehicleOwner { get; set; }
        public virtual DbSet<Motor_VehicleParking> Motor_VehicleParking { get; set; }
        public virtual DbSet<Person_BusinessType> Person_BusinessType { get; set; }
        public virtual DbSet<Person_ConvictionType> Person_ConvictionType { get; set; }
        public virtual DbSet<Person_EmpStat> Person_EmpStat { get; set; }
        public virtual DbSet<Person_MaritalStatus> Person_MaritalStatus { get; set; }
        public virtual DbSet<Person_Occupation> Person_Occupation { get; set; }
        public virtual DbSet<Person_RelationshipToProp> Person_RelationshipToProp { get; set; }
        public virtual DbSet<Person_Title> Person_Title { get; set; }
        public virtual DbSet<Policy_MotorPolicyInsurer> Policy_MotorPolicyInsurer { get; set; }
        public virtual DbSet<Property_Accommodation> Property_Accommodation { get; set; }
        public virtual DbSet<Property_Construction> Property_Construction { get; set; }
        public virtual DbSet<Property_HouseType> Property_HouseType { get; set; }
        public virtual DbSet<Property_Listed> Property_Listed { get; set; }
        public virtual DbSet<Property_PrimaryHeating> Property_PrimaryHeating { get; set; }
        public virtual DbSet<Property_RoofType> Property_RoofType { get; set; }
        public virtual DbSet<Property_Unoccupancy> Property_Unoccupancy { get; set; }
        public virtual DbSet<Security_LockTypes> Security_LockTypes { get; set; }
        public virtual DbSet<Security_PatiosNFrenchDoors> Security_PatiosNFrenchDoors { get; set; }
        public virtual DbSet<Security_WindowLockTypes> Security_WindowLockTypes { get; set; }
        public virtual DbSet<SpecifiedItem_Category> SpecifiedItem_Category { get; set; }
        public virtual DbSet<Property_AccommodationABI> Property_AccommodationABI { get; set; }
    }
}
