//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyCheck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motor_TrackerSecurityFitted
    {
        public string abiCode { get; set; }
        public string abiDescription { get; set; }
        public string vt { get; set; }
        public string vtCode { get; set; }
        public string vtDescription { get; set; }
    }
}
