//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyCheck.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ParagonEntities15 : DbContext
    {
        public ParagonEntities15()
            : base("name=ParagonEntities15")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<ClaimsUploadParagon_Result> ClaimsUploadParagon(string policyReference)
        {
            var policyReferenceParameter = policyReference != null ?
                new ObjectParameter("PolicyReference", policyReference) :
                new ObjectParameter("PolicyReference", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ClaimsUploadParagon_Result>("ClaimsUploadParagon", policyReferenceParameter);
        }
    
        public virtual ObjectResult<ClaimsUploadParagonBD_Result> ClaimsUploadParagonBD(string policyReference)
        {
            var policyReferenceParameter = policyReference != null ?
                new ObjectParameter("PolicyReference", policyReference) :
                new ObjectParameter("PolicyReference", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ClaimsUploadParagonBD_Result>("ClaimsUploadParagonBD", policyReferenceParameter);
        }
    
        public virtual ObjectResult<ClaimsUploadParagonNo_Result> ClaimsUploadParagonNo(string policyReference, Nullable<int> proposerNo)
        {
            var policyReferenceParameter = policyReference != null ?
                new ObjectParameter("PolicyReference", policyReference) :
                new ObjectParameter("PolicyReference", typeof(string));
    
            var proposerNoParameter = proposerNo.HasValue ?
                new ObjectParameter("ProposerNo", proposerNo) :
                new ObjectParameter("ProposerNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ClaimsUploadParagonNo_Result>("ClaimsUploadParagonNo", policyReferenceParameter, proposerNoParameter);
        }
    
        public virtual ObjectResult<PCProposersParagon1_Result> PCProposersParagon1(string policyReference)
        {
            var policyReferenceParameter = policyReference != null ?
                new ObjectParameter("PolicyReference", policyReference) :
                new ObjectParameter("PolicyReference", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PCProposersParagon1_Result>("PCProposersParagon1", policyReferenceParameter);
        }
    
        public virtual ObjectResult<PCProposersParagonBD1_Result> PCProposersParagonBD1(string policyReference)
        {
            var policyReferenceParameter = policyReference != null ?
                new ObjectParameter("PolicyReference", policyReference) :
                new ObjectParameter("PolicyReference", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PCProposersParagonBD1_Result>("PCProposersParagonBD1", policyReferenceParameter);
        }
    
        public virtual ObjectResult<PCProposersParagonBDNo_Result> PCProposersParagonBDNo(string policyReference, Nullable<int> proposerNo)
        {
            var policyReferenceParameter = policyReference != null ?
                new ObjectParameter("PolicyReference", policyReference) :
                new ObjectParameter("PolicyReference", typeof(string));
    
            var proposerNoParameter = proposerNo.HasValue ?
                new ObjectParameter("ProposerNo", proposerNo) :
                new ObjectParameter("ProposerNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PCProposersParagonBDNo_Result>("PCProposersParagonBDNo", policyReferenceParameter, proposerNoParameter);
        }
    
        public virtual ObjectResult<PCProposersParagonNo_Result> PCProposersParagonNo(string policyReference, Nullable<int> proposerNo)
        {
            var policyReferenceParameter = policyReference != null ?
                new ObjectParameter("PolicyReference", policyReference) :
                new ObjectParameter("PolicyReference", typeof(string));
    
            var proposerNoParameter = proposerNo.HasValue ?
                new ObjectParameter("ProposerNo", proposerNo) :
                new ObjectParameter("ProposerNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PCProposersParagonNo_Result>("PCProposersParagonNo", policyReferenceParameter, proposerNoParameter);
        }
    
        public virtual ObjectResult<PolicyCheckUploadParagon_Result> PolicyCheckUploadParagon(string policyReference)
        {
            var policyReferenceParameter = policyReference != null ?
                new ObjectParameter("PolicyReference", policyReference) :
                new ObjectParameter("PolicyReference", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PolicyCheckUploadParagon_Result>("PolicyCheckUploadParagon", policyReferenceParameter);
        }
    
        public virtual ObjectResult<PolicyCheckUploadParagonBD_Result> PolicyCheckUploadParagonBD(string policyReference)
        {
            var policyReferenceParameter = policyReference != null ?
                new ObjectParameter("PolicyReference", policyReference) :
                new ObjectParameter("PolicyReference", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PolicyCheckUploadParagonBD_Result>("PolicyCheckUploadParagonBD", policyReferenceParameter);
        }
    
        public virtual ObjectResult<PolicyCheckUploadParagonUpdate_Result> PolicyCheckUploadParagonUpdate(string policyReference)
        {
            var policyReferenceParameter = policyReference != null ?
                new ObjectParameter("PolicyReference", policyReference) :
                new ObjectParameter("PolicyReference", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PolicyCheckUploadParagonUpdate_Result>("PolicyCheckUploadParagonUpdate", policyReferenceParameter);
        }
    
        public virtual ObjectResult<SpecItemUploadParagon_Result> SpecItemUploadParagon(string policyReference)
        {
            var policyReferenceParameter = policyReference != null ?
                new ObjectParameter("PolicyReference", policyReference) :
                new ObjectParameter("PolicyReference", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpecItemUploadParagon_Result>("SpecItemUploadParagon", policyReferenceParameter);
        }
    
        public virtual ObjectResult<SpecItemUploadParagonBD_Result> SpecItemUploadParagonBD(string policyReference)
        {
            var policyReferenceParameter = policyReference != null ?
                new ObjectParameter("PolicyReference", policyReference) :
                new ObjectParameter("PolicyReference", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpecItemUploadParagonBD_Result>("SpecItemUploadParagonBD", policyReferenceParameter);
        }
    }
}
