//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyCheck.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class PolicyMain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PolicyMain()
        {
            this.CAllrisksBicycles = new HashSet<CAllrisksBicycle>();
            this.CSpecifiedItems1 = new HashSet<CSpecifiedItem>();
            this.MPClaimsLosses1 = new HashSet<MPClaimsLoss>();
            this.MPConvictions1 = new HashSet<MPConviction>();
            this.ProposerDetails = new HashSet<ProposerDetail>();
        }

        public int id { get; set; }
        [Display(Name = "Postcode:")]
        public string PPostCode { get; set; }

        [Display(Name = "YrBuilt:")]
        public Nullable<int> PYearBuilt { get; set; }

        [Display(Name = "Type:")]
        public string PTypeOfHouse { get; set; }

        [Display(Name = "Walls:")]
        public string PWalls { get; set; }

        [Display(Name = "Roof:")]
        public string PRoof { get; set; }

        [Display(Name = "Flat%:")]
        public Nullable<int> PFlatPercent { get; set; }

        [Display(Name = "Bedrooms:")]
        public Nullable<int> PBedrooms { get; set; }

        [Display(Name = "Rooms:")]
        public Nullable<int> PRooms { get; set; }

        [Display(Name = "Floors:")]
        public Nullable<int> PFloors { get; set; }

        public Nullable<int> PFlatFloor { get; set; }

        [Display(Name = "Bathrooms:")]
        public Nullable<int> PBathrooms { get; set; }

        [Display(Name = "Extended?")]
        public string PExtended { get; set; }

        [Display(Name = "Yr Extended:")]
        public int PYearExtended { get; set; }

        [Display(Name = "Heat P:")]
        public string PHeatingPrimary { get; set; }

        [Display(Name = "Heat S:")]
        public string PHeatingSecondary { get; set; }

        [Display(Name = "Prelim Qs>")]
        public string PPrelimQuestions { get; set; }

        [Display(Name = "Insurance Declined?")]
        public string PPqInsuranceDeclined { get; set; }

        [Display(Name = "Convictions?")]
        public string PPqConvictions { get; set; }

        [Display(Name = "Bankrupt?")]
        public string PPqBankrupt { get; set; }

        [Display(Name = "Storm/Flood?")]
        public string PPqStormFlood { get; set; }

        [Display(Name = "Subsidence?")]
        public string PPqSubsidence { get; set; }

        [Display(Name = "LandSlip?")]

        public string PPqLandslip { get; set; }

        [Display(Name = "Ground Heave?")]
        public string PPqGroundHeave { get; set; }

        [Display(Name = "In Good Repair?")]
        public string PPqInGoodRepair { get; set; }

        [Display(Name = "Near River/Quarry?")]
        public string PPqNearRiverQuarry { get; set; }

        [Display(Name = "RQ Distance")]
        public Nullable<int> PPqNearRQDistance { get; set; }

        [Display(Name = "Building Listed:")]
        public string PPqBuildingListed { get; set; }

        [Display(Name = "Repaired/Monitored?")]
        public string PPqRepairedMonitored { get; set; }

        [Display(Name = "Underpinned?")]
        public string PPqUnderpinned { get; set; }

        [Display(Name = "Use/Occupancy>")]
        public string PUseOccupancy { get; set; }

        [Display(Name = "Accomodation:")]
        public string PuoAccomodation { get; set; }

        [Display(Name = "Residence:")]
        public string PuoResidence { get; set; }

        [Display(Name = "Unoccupied:")]
        public string PuoUnnocupied { get; set; }

        [Display(Name = "Business Use:")]
        public string PuoBusinessUse { get; set; }

        [Display(Name = "Stock:")]
        public Nullable<int> PuoStock { get; set; }

        [Display(Name = "Equipment:")]
        public Nullable<int> PuoEquipment { get; set; }

        [Display(Name = "Holiday Home?")]
        public string PuoHolidayHome { get; set; }

        [Display(Name = "Paying Guests?")]
        public string PuoPayingGuests { get; set; }

        [Display(Name = "PG Number:")]
        public Nullable<int> PuoPGNumber { get; set; }

        [Display(Name = "Smokers?")]
        public string PuoSmokers { get; set; }

        [Display(Name = "Adults:")]
        public Nullable<int> PuoNooAdults { get; set; }

        [Display(Name = "Children")]
        public Nullable<int> PuoNooChildren { get; set; }

        [Display(Name = "Security>")]
        public string PSecurity { get; set; }

        [Display(Name = "Final Exit Doors")]
        public string PsFinalExitDoors { get; set; }

        [Display(Name = "Other Doors?")]
        public string PsOtherDoors { get; set; }

        [Display(Name = "Patio Doors")]
        public string PsPatioDoors { get; set; }

        [Display(Name = "Windows?")]
        public string PsWindows { get; set; }

        [Display(Name = "NHood Watch?")]
        public string PsNeighbourhoodWatch { get; set; }

        [Display(Name = "Smoke Alarm?")]
        public string PsSmokeAlarm { get; set; }

        [Display(Name = "Self Contained?")]
        public string PsSelfContained { get; set; }

        [Display(Name = "Intruder Alarm?")]
        public string PsIntruderAlarm { get; set; }

        [Display(Name = "Alarm Type:")]
        public string PsAlarmType { get; set; }

        [Display(Name = "Accred Details (1):")]
        public string PsAccredationDetailsOne { get; set; }

        [Display(Name = "AD (1) Other:")]
        public string PsAccredationDetailsOneOther { get; set; }

        [Display(Name = "Spec Contract?")]
        public string PsSpecificationContract { get; set; }


        [DataType(DataType.Date)]
        [Display(Name = "Date Installed:")]
        public Nullable<System.DateTime> PsDateInstalled { get; set; }


        [Display(Name = "Maintainer:")]
        public string PsMaintainer { get; set; }

        [Display(Name = "Maintainer Oth:")]
        public string PsMaintainerTwo { get; set; }

        [Display(Name = "Accred Details(2):")]
        public string PsAccreditationDetailsTwo { get; set; }

        [Display(Name = "AD (2) Free Text")]
        public string PsAccredationDetailsTwoOther { get; set; }




        [Display(Name = "Survey/Reports>")]
        public string PsrSecurityReports { get; set; }

        [Display(Name = "RICS/FSVA SURVEY?")]
        public string PsrRICSFSVASURVEY { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Date:")]
        public Nullable<System.DateTime> PsrRFSDate { get; set; }

        [Display(Name = "Surveyor's Name:")]
        public string PsrRFSSurveyorsName { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Date Proof Rec:")]
        public string PsrRFSDateProofRec { get; set; }

        [Display(Name = "Struct Engineer Report?")]
        public string PsrStructuralER { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Date:")]
        public Nullable<System.DateTime> PsrStructuralERDate { get; set; }

        [Display(Name = "Engineer's Name:")]
        public string PsrStructuralEnginnersName { get; set; }

        [Display(Name = "NHBC GUARANTEE")]
        public string PsrNHBCguarantee { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Date:")]
        public Nullable<System.DateTime> PsrExpires { get; set; }

        [Display(Name = "Oth Dets>")]
        public string POtherDetails { get; set; }

        [Display(Name = "Sex:")]
        public string MpSex { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "DOB:")]
        public Nullable<System.DateTime> MpDOB { get; set; }




        public Nullable<int> MpAge { get; set; }

        [Display(Name = "Employ Details>")]
        public string EmployDetails { get; set; }

        [Display(Name = "Occ 1:")]
        public string MpEDOccOne { get; set; }

        [Display(Name = "Business:")]
        public string MpEDOccOneBusiness { get; set; }

        [Display(Name = "Status:")]
        public string MpEDOccOneStatus { get; set; }

        [Display(Name = "Full/Part:")]
        public string MpEDOccOneFullPart { get; set; }

        [Display(Name = "Occ 2:")]
        public string MpEDOccTwo { get; set; }

        [Display(Name = "Business:")]
        public string MpEDOccTwoBusiness { get; set; }

        [Display(Name = "Status:")]
        public string MpEDOccTwoStatus { get; set; }

        [Display(Name = "Full/Part")]
        public string MpEDOccTwoFullPart { get; set; }

        [Display(Name = "Personal Details>")]
        public string MpPersonalDetails { get; set; }

        [Display(Name = "Title:")]
        public string MpPersonalDetailsTitle { get; set; }

        [Display(Name = "Surname:")]
        public string MpSurname { get; set; }

        [Display(Name = "Forenames:")]
        public string MpForenames { get; set; }

        [Display(Name = "At Risk Address?")]
        public string MpAtRiskAddress { get; set; }

        [Display(Name = "First Time Buyer?")]
        public string MpFirstTimeBuyer { get; set; }

        [Display(Name = "Convictions>")]
        public string MpConvictions { get; set; }

        [Display(Name = "Claims/Losses>")]
        public string MpClaimsLosses { get; set; }

        [Display(Name = "Buildings & Contents>")]
        public string CBuildingsAndContents { get; set; }

        [Display(Name = "Cover Type:")]
        public string CBCoverType { get; set; }

        [Display(Name = "Sum Insured:")]
        public Nullable<int> CBSumInsured { get; set; }

        [Display(Name = "Vol Excess:")]
        public Nullable<int> CBVolExcess { get; set; }

        [Display(Name = "XS Buy Back>")]
        public string CBXSBuyBack { get; set; }

        [Display(Name = "Prev Insurer>")]
        public string CBPrevInsurer { get; set; }

        [Display(Name = "Cover Type:")]
        public string CCCoverType { get; set; }

        [Display(Name = "Sum Insured Value")]
        public Nullable<int> CCSumInsuredValue { get; set; }

        [Display(Name = "Sum Insured 1 Item")]
        public Nullable<int> CCSumInsuredOneItem { get; set; }

        [Display(Name = "Valuables Value")]
        public Nullable<int> CCValuablesValue { get; set; }

        [Display(Name = "Valuables 1 Item")]
        public Nullable<int> CCValuablesOneItem { get; set; }

        [Display(Name = "Vol Excess")]
        public Nullable<int> CCVolExcess { get; set; }

        [Display(Name = "XS Buy Back?")]
        public string CCXSBuyBack { get; set; }

        [Display(Name = "Prev Insurer >")]
        public string CCPrevInsurer { get; set; }

        [Display(Name = "Buildings Total")]
        public Nullable<int> CBSummationBuildingCoverEnteredDetails { get; set; }

        [Display(Name = "Buildings Xs")]
        public Nullable<int> CBBuildingsVolExcessEnteredDetails { get; set; }

        [Display(Name = "Content Total")]
        public Nullable<int> CCSummationContentsCoverEntered { get; set; }

        [Display(Name = "Contents Xs")]
        public string CCContentsVolExcessEnteredDetails { get; set; }

        [Display(Name = "All Risks>")]
        public string CAllRisks { get; set; }
        public Nullable<int> CAllRiskUnspecEffectsValue { get; set; }
        public Nullable<int> CAllRiskUnspecEffectsOneItem { get; set; }
        public string CAllRiskUnspecEffectsTerritory { get; set; }
        public Nullable<int> CAllRisksValuablesUnspecValue { get; set; }
        public Nullable<int> CAllRisksValuablesUnspecOneItem { get; set; }
        public string CAllRisksValuablesUnspecTerritory { get; set; }
        public Nullable<int> CAllRisksPhotoUnspecValue { get; set; }
        public Nullable<int> CAllRisksPhotoUnspecOneItem { get; set; }
        public string CAllRisksPhotoUnspecTerritory { get; set; }
        public Nullable<int> CAllRisksSportsUnspecValue { get; set; }
        public Nullable<int> CAllRisksSportsUnspecOneItem { get; set; }
        public string CAllRisksSportsUnspecTerritory { get; set; }
        public string CAllRiskBicycles { get; set; }
        public Nullable<int> CAllRisksMoneyValue { get; set; }
        public string CAllRisksMoneyTerritory { get; set; }
        public Nullable<int> CAllRisksCreditCardsValue { get; set; }
        public string CAllRiskCreditCardsTerritory { get; set; }
        public Nullable<int> CAllRisksFreezerContentsValue { get; set; }
        public int CAllRisksFreezerContentsAge { get; set; }

        [Display(Name = "Spec Items>")]
        public string CSpecifiedItems { get; set; }

        [Display(Name = "Legal Expenses")]
        public string AOLegalExpenses { get; set; }

        [Display(Name = "Motor Policy")]
        public string AOMotorPolicy { get; set; }

        [Display(Name = "Motor Insurer")]
        public string AOCurrentMotorInsurer { get; set; }

        [Display(Name = "Caravans>")]
        public string AOCaravans { get; set; }

        [Display(Name = "Boats>")]
        public string AOBoats { get; set; }

        [Display(Name = "Searches Cons>")]
        public string AOSearchesConsent { get; set; }

        [Display(Name = "Scheme No:")]
        public string AOSchemeNo { get; set; }

        [Display(Name = "Cover Date:")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> AOCoverDate { get; set; }

        [Display(Name = "Total:")]
        public Nullable<int> AOSummationCaravansEnteredDetails { get; set; }

        [Display(Name = "Total:")]
        public Nullable<int> AOSummationBoatEnteredDetails { get; set; }

        public virtual AOBoatDetail AOBoatDetail { get; set; }
        public virtual AOCaravanDetail AOCaravanDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAllrisksBicycle> CAllrisksBicycles { get; set; }
        public virtual CBuildingsPrevInsurance CBuildingsPrevInsurance { get; set; }
        public virtual CCContentsPrevInsurance CCContentsPrevInsurance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSpecifiedItem> CSpecifiedItems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MPClaimsLoss> MPClaimsLosses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MPConviction> MPConvictions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProposerDetail> ProposerDetails { get; set; }
        public virtual PropertyODCommunicationAddress PropertyODCommunicationAddress { get; set; }
        public virtual PropertyODInterestedParty PropertyODInterestedParty { get; set; }
        public virtual PropertyODRiskPropertyAddress PropertyODRiskPropertyAddress { get; set; }
        public virtual PolicyMain PolicyMain1 { get; set; }
        public virtual PolicyMain PolicyMain2 { get; set; }

        public IEnumerable<CAllrisksBicycle> Bicycles { get; set; }

        public List<CSpecifiedItem> SpecifiedItems { get; set; }

        public List<MPClaimsLoss> ClaimsLosses { get; set; }

        public List<MPConviction> Convictions { get; set; }

        public List<ProposerDetail> PropDetails { get; set; }

        public IEnumerable<SelectListItem> HouseType { get; set; }

        public IEnumerable<SelectListItem> Walls { get; set; }

        public IEnumerable<SelectListItem> Roof { get; set; }

        public IEnumerable<SelectListItem> yesNo { get; set; }

        public IEnumerable<SelectListItem> Heating { get; set; }

        public IEnumerable<SelectListItem> Sex { get; set; }

        public IEnumerable<SelectListItem> BuildingListed { get; set; }

        public IEnumerable<SelectListItem> Accomodation { get; set; }

        public IEnumerable<SelectListItem> Residence { get; set; }

        public IEnumerable<SelectListItem> Unoccupied { get; set; }

        public IEnumerable<SelectListItem> BusinessUse { get; set; }

        public IEnumerable<SelectListItem> AlarmType { get; set; }

        public IEnumerable<SelectListItem> AccredDetails { get; set; }

        public IEnumerable<SelectListItem> MaintainerCompany { get; set; }

        public IEnumerable<SelectListItem> InterestedParty { get; set; }

        public IEnumerable<SelectListItem> InterestedPartyType { get; set; }

        public IEnumerable<SelectListItem> BuildingsCoverType { get; set; }

        public IEnumerable<SelectListItem> ContentsCoverType { get; set; }

        public IEnumerable<SelectListItem> PreviousInsurer { get; set; }

        public IEnumerable<SelectListItem> ProofOfInsurerPayment { get; set; }

        public IEnumerable<SelectListItem> Occupation { get; set; }

        public IEnumerable<SelectListItem> BusinessType { get; set; }

        public IEnumerable<SelectListItem> Status { get; set; }

        public IEnumerable<SelectListItem> Time { get; set; }

        public IEnumerable<SelectListItem> Title { get; set; }

        public IEnumerable<SelectListItem> CaravanType { get; set; }

        public IEnumerable<SelectListItem> EngineType { get; set; }

        public IEnumerable<SelectListItem> BoatClass { get; set; }

        public IEnumerable<SelectListItem> Territory { get; set; }

    }
}
