//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyCheck.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PolicyCheckEntities53 : DbContext
    {
        public PolicyCheckEntities53()
            : base("name=PolicyCheckEntities53")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AOBoatDetail> AOBoatDetails { get; set; }
        public virtual DbSet<AOCaravanDetail> AOCaravanDetails { get; set; }
        public virtual DbSet<CAllrisksBicycle> CAllrisksBicycles { get; set; }
        public virtual DbSet<CBuildingsPrevInsurance> CBuildingsPrevInsurances { get; set; }
        public virtual DbSet<CCContentsPrevInsurance> CCContentsPrevInsurances { get; set; }
        public virtual DbSet<CSpecifiedItem> CSpecifiedItems { get; set; }
        public virtual DbSet<MPClaimsLoss> MPClaimsLosses { get; set; }
        public virtual DbSet<MPConviction> MPConvictions { get; set; }
        public virtual DbSet<PolicyMain> PolicyMains { get; set; }
        public virtual DbSet<PropertyODCommunicationAddress> PropertyODCommunicationAddresses { get; set; }
        public virtual DbSet<PropertyODInterestedParty> PropertyODInterestedParties { get; set; }
        public virtual DbSet<PropertyODRiskPropertyAddress> PropertyODRiskPropertyAddresses { get; set; }
        public virtual DbSet<ProposerDetail> ProposerDetails { get; set; }
    }
}
