//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyCheck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyODCommunicationAddress
    {
        public int CommunicationAddressPolicyId { get; set; }
        public string CANumberName { get; set; }
        public string CAStreet { get; set; }
        public string CATown { get; set; }
        public string CACounty { get; set; }
        public string CAPostCode { get; set; }
    
        public virtual PolicyMain PolicyMain { get; set; }
    }
}
