//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyCheck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property_AccommodationABI
    {
        public int ID { get; set; }
        public string MisysCode { get; set; }
        public string MisysName { get; set; }
        public string ABICode { get; set; }
        public string ABIDescription { get; set; }
        public string MappingField { get; set; }
    }
}
