//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicyCheck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyODInterestedParty
    {
        public int InterestedPartyPolicyId { get; set; }
        public string IPType { get; set; }
        public string IPName { get; set; }
        public string IPNameOther { get; set; }
        public string IPNumberName { get; set; }
        public string IPStreet { get; set; }
        public string IPTown { get; set; }
        public string IPCounty { get; set; }
        public string IPPostCode { get; set; }
        public string IPRefMortgageNo { get; set; }
    
        public virtual PolicyMain PolicyMain { get; set; }
    }
}
